Drop Ruby 1.9.3 support, add Ruby 2.3.0 & 2.4.1 tests
sensu-plugins/sensu-plugins-rethinkdb pull request #3
Opened 2017-07-15 14:10 UTC by thomasriley

## Pull Request Checklist

sensu-plugins/sensu-plugins-feature-requests#27

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [ ] Existing tests pass 

#### Purpose
- Drop Ruby 1.9.3 support
- Add Ruby 2.3.0 & 2.4.1 testing

#### Known Compatablity Issues
- Breaks support for Ruby 1.9.3 users

2017-07-15 18:02 UTC, majormoses requested changes
Overall looks good, just one minor nitpick.

2017-07-15 18:02 UTC, majormoses commented on CHANGELOG.md
> +#Change Log
put a space between `#` and `Changelog` so its a header.

2017-07-15 18:07 UTC, thomasriley commented on CHANGELOG.md
> +#Change Log
Whoops. Well spotted 👍

2017-07-15 18:14 UTC, majormoses approved these changes

2017-07-15 18:19 UTC, majormoses commented
travis is taking a while if I don't circle back to this in 24 hours ping me.

https://travis-ci.org/sensu-plugins/sensu-plugins-rethinkdb/builds/253972113

2017-07-15 18:26 UTC, majormoses commented
canceled and restarted job, looks good now.

2017-07-15 18:26 UTC, merged

2017-07-15 18:47 UTC, majormoses commented
this plugin has had no love in a while, nothing was tagged and I doubt anything was actually tagged. I did some cleanup and at least tagged the version deployed to rubygems.org

2017-07-15 18:52 UTC, majormoses commented
looks like we dont have access to that gem, will ping the owner.

2017-07-15 18:53 UTC, majormoses commented
looks like we have tried #2

2017-07-18 15:32 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-rethinkdb/versions/1.0.0